### ISSUE TITLE
Error when starting 

### ISSUE THREAD

**Issue by XenomMayFire** [kirillweb/localtunnel-restarter#1]
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/localtunnel-restarter-0.1.2/lib/localtunnel/restarter/cli.rb:7:in `run': uninitialized constant Localtunnel::Restarter::CLI::OptionParser (NameError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/localtunnel-restarter-0.1.2/bin/localtunnel-restarter:9:in `<top (required)>'
        from C:/Ruby23-x64/bin/localtunnel-restarter:22:in `load'
        from C:/Ruby23-x64/bin/localtunnel-restarter:22:in `<main>'

**Comment by kirillshevch** [comment]
@XenomMayFire Gem isn't compatible with Windows

**Comment by qbarbosa** [comment]
Hi @kirillshevch , I have exactly the same error on a Debian 8 server.

```
➜  ~ localtunnel-restarter --port 80 --subdomain mydomain
/var/lib/gems/2.1.0/gems/localtunnel-restarter-0.1.2/lib/localtunnel/restarter/cli.rb:7:in `run': uninitialized constant Localtunnel::Restarter::CLI::OptionParser (NameError)
	from /var/lib/gems/2.1.0/gems/localtunnel-restarter-0.1.2/bin/localtunnel-restarter:9:in `<top (required)>'
	from /usr/local/bin/localtunnel-restarter:22:in `load'
	from /usr/local/bin/localtunnel-restarter:22:in `<main>'
```

Seems like the script can't find `OptionParser`, could you help me please?

**Comment by kirillshevch** [comment]
Hi @quentinsikana 
Try to install 0.1.4 version

**Comment by qbarbosa** [comment]
I added `require 'optparse'` in the bin file and it seems to solve this.

Just opened PR #2 with this modification.

PS : Ok, you're super fast ! 👍
